//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTheFlyWPFC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class custodyTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public custodyTBL()
        {
            this.invoiceTBLs = new HashSet<invoiceTBL>();
        }
    
        public int custodyID { get; set; }
        public int ownerID { get; set; }
        public decimal amount { get; set; }
        public bool active { get; set; }
        public int invoiceID { get; set; }
    
        public virtual EmployeeTBL EmployeeTBL { get; set; }
        public virtual invoiceTBL invoiceTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoiceTBL> invoiceTBLs { get; set; }
    }
}
