//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTheFlyWPFC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customerTBL()
        {
            this.invoiceTBLs = new HashSet<invoiceTBL>();
        }
    
        public int customerID { get; set; }
        public string name { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public string cityID { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> add_date { get; set; }
        public Nullable<decimal> credit { get; set; }
    
        public virtual LibyanCitiesTBL LibyanCitiesTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoiceTBL> invoiceTBLs { get; set; }
    }
}
