//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTheFlyWPFC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryServiceTBL
    {
        public int deliveryServiceID { get; set; }
        public int invoiceID { get; set; }
        public int categoryID { get; set; }
        public int vendorBranchID { get; set; }
        public Nullable<int> customerID { get; set; }
        public bool isFullTrip { get; set; }
        public Nullable<decimal> productPrice { get; set; }
        public decimal deliveryPrice { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> availabilityDay { get; set; }
    
        public virtual CategoriesTBL CategoriesTBL { get; set; }
        public virtual CustomerTBL CustomerTBL { get; set; }
        public virtual invoiceTBL invoiceTBL { get; set; }
        public virtual VendorBranchTBL VendorBranchTBL { get; set; }
    }
}
