//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTheFlyWPFC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryPricesTBL
    {
        public int deliveryPricesID { get; set; }
        public Nullable<int> categoryID { get; set; }
        public string customerLocation { get; set; }
        public string vendorLocation { get; set; }
        public Nullable<decimal> fullTripPrice { get; set; }
        public Nullable<decimal> halfTripPrice { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual CategoriesTBL CategoriesTBL { get; set; }
        public virtual LibyanCitiesTBL LibyanCitiesTBL { get; set; }
        public virtual LibyanCitiesTBL LibyanCitiesTBL1 { get; set; }
    }
}
