//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTheFlyWPFC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeTBL()
        {
            this.custodyTBLs = new HashSet<custodyTBL>();
            this.deliveryTBLs = new HashSet<deliveryTBL>();
            this.userTBLs = new HashSet<userTBL>();
        }
    
        public int employeeID { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public string address { get; set; }
        public bool active { get; set; }
        public int jobID { get; set; }
        public string cityID { get; set; }
        public System.DateTime start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> branchID { get; set; }
    
        public virtual CompanyBranchTBL CompanyBranchTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<custodyTBL> custodyTBLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deliveryTBL> deliveryTBLs { get; set; }
        public virtual JobsTBL JobsTBL { get; set; }
        public virtual LibyanCitiesTBL LibyanCitiesTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userTBL> userTBLs { get; set; }
    }
}
