//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTheFlyWPFC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvoiceTBL()
        {
            this.DeliveryTBLs = new HashSet<DeliveryTBL>();
            this.serviceTBLs = new HashSet<serviceTBL>();
        }
    
        public int invoiceID { get; set; }
        public int issuerID { get; set; }
        public Nullable<int> custodyID { get; set; }
        public int customerID { get; set; }
        public System.TimeSpan time { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> branchID { get; set; }
    
        public virtual CompanyBranchTBL CompanyBranchTBL { get; set; }
        public virtual CustodyTBL CustodyTBL { get; set; }
        public virtual CustomerTBL CustomerTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryTBL> DeliveryTBLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<serviceTBL> serviceTBLs { get; set; }
    }
}
