//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTheFlyWPFC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembershipTBL
    {
        public int membershipID { get; set; }
        public string name { get; set; }
        public int customerID { get; set; }
        public int vendorID { get; set; }
    
        public virtual CustomerTBL CustomerTBL { get; set; }
        public virtual VendorTBL VendorTBL { get; set; }
    }
}
