//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTheFlyWPFC.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnTheFlyDBEntities : DbContext
    {
        public OnTheFlyDBEntities()
            : base("name=OnTheFlyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoriesTBL> CategoriesTBLs { get; set; }
        public virtual DbSet<CompanyBranchTBL> CompanyBranchTBLs { get; set; }
        public virtual DbSet<custodyTBL> custodyTBLs { get; set; }
        public virtual DbSet<CustomerTBL> CustomerTBLs { get; set; }
        public virtual DbSet<DeliveryPricesTBL> DeliveryPricesTBLs { get; set; }
        public virtual DbSet<DeliveryServiceTBL> DeliveryServiceTBLs { get; set; }
        public virtual DbSet<deliveryStatusTBL> deliveryStatusTBLs { get; set; }
        public virtual DbSet<deliveryTBL> deliveryTBLs { get; set; }
        public virtual DbSet<EmployeeTBL> EmployeeTBLs { get; set; }
        public virtual DbSet<FinanceTBL> FinanceTBLs { get; set; }
        public virtual DbSet<invoiceTBL> invoiceTBLs { get; set; }
        public virtual DbSet<JobsTBL> JobsTBLs { get; set; }
        public virtual DbSet<LibyanCitiesTBL> LibyanCitiesTBLs { get; set; }
        public virtual DbSet<MembershipTBL> MembershipTBLs { get; set; }
        public virtual DbSet<PayrollTBL> PayrollTBLs { get; set; }
        public virtual DbSet<QuickDeliveryServiceTBL> QuickDeliveryServiceTBLs { get; set; }
        public virtual DbSet<ServiceTBL> ServiceTBLs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<userGroupRoleTBL> userGroupRoleTBLs { get; set; }
        public virtual DbSet<UserGroupTBL> UserGroupTBLs { get; set; }
        public virtual DbSet<UserTBL> UserTBLs { get; set; }
        public virtual DbSet<VehicleTBL> VehicleTBLs { get; set; }
        public virtual DbSet<VehicleTypeTBL> VehicleTypeTBLs { get; set; }
        public virtual DbSet<VendorBranchTBL> VendorBranchTBLs { get; set; }
        public virtual DbSet<VendorServicesTBL> VendorServicesTBLs { get; set; }
        public virtual DbSet<VendorTBL> VendorTBLs { get; set; }
        public virtual DbSet<SettingsTBL> SettingsTBLs { get; set; }
    }
}
