//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTheFlyWPFC.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnTheFlyDBEntities : DbContext
    {
        public OnTheFlyDBEntities()
            : base("name=OnTheFlyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarsTBL> CarsTBLs { get; set; }
        public virtual DbSet<CategoriesTBL> CategoriesTBLs { get; set; }
        public virtual DbSet<CompanyBranchTBL> CompanyBranchTBLs { get; set; }
        public virtual DbSet<custodyTBL> custodyTBLs { get; set; }
        public virtual DbSet<customerTBL> customerTBLs { get; set; }
        public virtual DbSet<deliveryStatusTBL> deliveryStatusTBLs { get; set; }
        public virtual DbSet<deliveryTBL> deliveryTBLs { get; set; }
        public virtual DbSet<EmployeeTBL> EmployeeTBLs { get; set; }
        public virtual DbSet<FinanceTBL> FinanceTBLs { get; set; }
        public virtual DbSet<invoiceTBL> invoiceTBLs { get; set; }
        public virtual DbSet<JobsTBL> JobsTBLs { get; set; }
        public virtual DbSet<LibyanCitiesTBL> LibyanCitiesTBLs { get; set; }
        public virtual DbSet<serviceTBL> serviceTBLs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<userGroupRoleTBL> userGroupRoleTBLs { get; set; }
        public virtual DbSet<userTBL> userTBLs { get; set; }
        public virtual DbSet<vendorBranchTBL> vendorBranchTBLs { get; set; }
        public virtual DbSet<vendorTBL> vendorTBLs { get; set; }
    }
}
