//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTheFlyWPFC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class payrollTBL
    {
        public int payrollID { get; set; }
        public int employeeID { get; set; }
        public Nullable<int> number_of_worked_days { get; set; }
        public Nullable<decimal> bonus { get; set; }
        public Nullable<decimal> overtime_pay { get; set; }
        public Nullable<decimal> cash_advance { get; set; }
        public Nullable<int> late_hours { get; set; }
        public Nullable<int> absent_days { get; set; }
        public decimal total_deduction { get; set; }
        public decimal total_addition { get; set; }
        public decimal gross_salary { get; set; }
        public int payroll_month { get; set; }
        public int payroll_year { get; set; }
        public bool paid { get; set; }
    
        public virtual EmployeeTBL EmployeeTBL { get; set; }
    }
}
