//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTheFlyWPFC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuickDeliveryServiceTBL
    {
        public int qDeliveryServiceID { get; set; }
        public int invoiceID { get; set; }
        public string categoryName { get; set; }
        public string distination { get; set; }
        public Nullable<bool> isFullTrip { get; set; }
        public Nullable<decimal> productPrice { get; set; }
        public Nullable<decimal> deliveryPrice { get; set; }
        public string customerName { get; set; }
        public Nullable<int> customerPhone { get; set; }
        public string customerAddress { get; set; }
        public string cityName { get; set; }
    
        public virtual invoiceTBL invoiceTBL { get; set; }
    }
}
