//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTheFlyWPFC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class serviceTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public serviceTBL()
        {
            this.InvoiceTBLs = new HashSet<InvoiceTBL>();
        }
    
        public int serviceID { get; set; }
        public string name { get; set; }
        public Nullable<int> categoryID { get; set; }
        public bool active { get; set; }
        public string customerLocation { get; set; }
        public string vendorLocation { get; set; }
        public Nullable<decimal> fullTripPrice { get; set; }
        public Nullable<decimal> halfTripPrice { get; set; }
    
        public virtual CategoriesTBL CategoriesTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceTBL> InvoiceTBLs { get; set; }
    }
}
