//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTheFlyWPFC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingsTBL
    {
        public int settingID { get; set; }
        public string name { get; set; }
        public Nullable<decimal> value_money { get; set; }
        public Nullable<int> value_int { get; set; }
        public string code { get; set; }
    }
}
