//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTheFlyWPFC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroupTBL
    {
        public int userID { get; set; }
        public int groupID { get; set; }
    
        public virtual userGroupRoleTBL userGroupRoleTBL { get; set; }
        public virtual UserTBL UserTBL { get; set; }
    }
}
