//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTheFlyWPFC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleTBL()
        {
            this.DeliveryTBLs = new HashSet<DeliveryTBL>();
        }
    
        public int vehicleID { get; set; }
        public Nullable<int> typeID { get; set; }
        public string plate_number { get; set; }
        public string made_company { get; set; }
        public int made_year { get; set; }
        public string edition_name { get; set; }
        public Nullable<int> branchID { get; set; }
        public bool state { get; set; }
    
        public virtual CompanyBranchTBL CompanyBranchTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryTBL> DeliveryTBLs { get; set; }
        public virtual VehicleTypeTBL VehicleTypeTBL { get; set; }
    }
}
