//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTheFlyWPFC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendorTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vendorTBL()
        {
            this.MembershipTBLs = new HashSet<MembershipTBL>();
            this.VendorBranchTBLs = new HashSet<VendorBranchTBL>();
            this.VendorServicesTBLs = new HashSet<VendorServicesTBL>();
        }
    
        public int vendorID { get; set; }
        public Nullable<int> categoryID { get; set; }
        public bool active { get; set; }
        public string name { get; set; }
    
        public virtual CategoriesTBL CategoriesTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MembershipTBL> MembershipTBLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorBranchTBL> VendorBranchTBLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorServicesTBL> VendorServicesTBLs { get; set; }
    }
}
